name: elastic
services:
  elasticsearch:
    image: elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:8.17.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic

  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - elastic

  postgres-connector:
    image: docker.elastic.co/integrations/elastic-connectors:8.17.4
    volumes:
      - ./config:/config
    environment:
      - "-tty --rm"
    command: "/app/bin/elastic-ingest -c /config/postgres-connector-config.yml"
    networks:
      - elastic

volumes:
  elastic:
    driver: local
  data:
    driver: local

networks:
  elastic:
    driver: bridge