services:

  vault:
    image: hashicorp/vault:latest
    hostname: vault
    container_name: vault
    ports:
      - 8200:8200
    volumes:
      - ./vault:/vault
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json