services:
  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - postgres_network

volumes:
  data:
    driver: local

networks:
  postgres_network:
    driver: bridge